### ISSUE TITLE
Гл. 2. Проверь себя

### ISSUE THREAD

**Issue by alex7716** [DimaS64/Big-Brain-programming#8]
1. Как  объяснить интерпретатору, что переменная представляет собой не число а строку (набор символов)
3. Имена TEATHER and TEATHEr принадлежат одной или разным переменным?
4. Одинаковы ли для интерпретатора Python записи 'Blah' and "Blah"?
5. считает ли интерпретатор, что '4' равно 4?
6. какое из имен не допустимо? почему?
- Teather2
- 2Teather
- teather_25
- TeaCher

**Comment by DimaS64** [comment]
1.Вставити набір символів в квадратні дужки

**Comment by DimaS64** [comment]
Не в квадратні  а в трійні

**Comment by DimaS64** [comment]
2.Звичайно можна.
3.До різних
4.ні
5.ні , тому,що вона взята в дужки, а це означає,що це текст а не число
6.3 тому що в назвах перемінних в інтерпритаторі забонені _
7.Строка
