### ISSUE TITLE
Гл 3 поверь себя

### ISSUE THREAD

**Issue by alex7716** [DimaS64/Big-Brain-programming#9]
1. Каким символом в Питон отображается умножение?
2. Какой ответ даст интерпретатор при операции 8 / 3?
3. как получить остаток при делении 8 / 3?
4. Как   получить результат деления  8 / 3 в десятичной форме?
5. Как  еще  в Питон можно вычислить 6*6*6*6?
6. как  записать число 17000000 в экспотенциальном представлении
7. Как  будет  выглядеть  число 4.56е-5 в обічном представлении (без символа Е)?

**Comment by DimaS64** [comment]
1. *
2. 2
3. 8.0/3

**Comment by DimaS64** [comment]
3. 8%3
4. 8.0/3
5. 6**4
6.

**Comment by alex7716** [comment]
залишились без відповіді:
6. как записать число 17000000 в экспотенциальном представлении
7 Как будет выглядеть число 4.56е-5 в обічном представлении (без символа Е)?

**Comment by DimaS64** [comment]
6. 17*10**6
7. 0,00000456
